### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Getauscht** [WeiWuxianYI/animemoon#4]
Hello, sorry to bother! But I am having some problems with the "HTTP Error 500", where whenever I try to make a request of the type put it returns this error.
As far as I handled the site, the error is introduced in the Account Creation part, and when I try to add some new work manually.
Another mistake I have is, even after uploading an episode with the links it is not found on the site; I get a 404 error. And lastly, I have the problem of the Panel being accessible by any user!

**Comment by WeiWuxianYI** [comment]
> Hello, sorry to bother! But I am having some problems with the "HTTP Error 500", where whenever I try to make a request of the type put it returns this error.
> As far as I handled the site, the error is introduced in the Account Creation part, and when I try to add some new work manually.
> Another mistake I have is, even after uploading an episode with the links it is not found on the site; I get a 404 error. And lastly, I have the problem of the Panel being accessible by any user!

Something is indeed wrong with .htaccess part. I have no idea whats wrong with it, and yes admin panel isn't suppose to be open by a regular user. I don't know whats wrong with it.

Make sure you use SSL and got HTTPS

**Comment by Yolomic** [comment]
Any fix?  would be usefull

**Comment by Getauscht** [comment]
No changes, and will likely remain so. As the developer himself said, because it was created for an old version of PHP, keeping updates is impractical. If someday some good soul comes along who understands PHP, and refactor the code will be very welcome!
